project:
  name: emdb
log:
  path: "../../logs/"
  level: "Info"
debug:
  local: true
  dev: true
  test: false
  release: false
server:
  domain:
    local: http://127.0.0.1:8088
    dev: https://dev-xmdb.emmai.com
    test: https://test-xmdb.emmai.com
    release: https://xmdb.emmai.com
  host:
    local: 127.0.0.1
    dev: 127.0.0.1
    test: 127.0.0.1
    release: 127.0.0.1
  port:
    local: 8088
    dev: 8088
    test: 8088
    release: 8088
  pass_mixin: "0x00544"
pgsql:
  local: >-
    postgresql://postgres:emdb2scjdl@localhost:5432/emdb2
  dev: >-
    postgresql://emmai_dev:TeMaqdpWz6ctya3inh@pgm-j6ce6pcj427n7i5r.pg.rds.aliyuncs.com/emdb
  test: >-
    postgresql://emmai:fsv33inhTeHkhY5@8.218.184.1:54321/emdb
  release: >-
    postgresql://emmai_prod:nhTeHkhY5MaqdpW2b@pgm-j6c277hnh814e491.pg.rds.aliyuncs.com/emdb
swagger:
  path: '/path/to/swagger'
  ui_path: '/path/to/swagger-ui'
emmai:
  base_url:
    local: http://localhost:8000
    dev: https://dev-api.emmai.com
    test: https://test-api.emmai.com
    release: https://api.emmai.com

