project:
  name: emdb
log:
  path: "../../logs/"
  level: "Info"
debug:
  local: true
  dev: true
  test: false
  release: false
server:
  domain:
    local: http://127.0.0.1
    dev: https://xmdb.likn.co
    test: https://test-xmdb.emmai.com
    release: https://xmdb.emmai.com
  host:
    local: 127.0.0.1
    dev: 127.0.0.1
    test: 127.0.0.1
    release: 127.0.0.1
  port:
    local: 8088
    dev: 8088
    test: 8088
    release: 8088
  pass_mixin: "0x00544"
pgsql:
  local: >-
    postgresql://postgres:emdb2scjdl@localhost:5432/emdb2
  dev:  >-
    postgresql://postgres:8BR53B9ErGweQH@43.207.219.44:5432/emdb
  test: >-
    postgresql://emmai:fsv33inhTeHkhY5@pgm-j6ch0p61yvj4fk25.pg.rds.aliyuncs.com:5432/emdb
  release: >-
    postgresql://user:pwd@host:5432/emdb
swagger:
  path: '/path/to/swagger'
  ui_path: '/path/to/swagger-ui'
emmai:
  base_url:
    local: http://localhost:8000
    dev: https://emmai-api.likn.co
    test: https://test-api.emmai.com
    release: https://api.emmai.com

