project:
  name: emdb
log:
  path: "../../logs/"
  level: "Info"
debug:
  dev: true
  prod: false
server:
  domain:
    dev: 127.0.0.1
    prod: https://tracker.likn.co
  host:
    dev: 127.0.0.1
    prod: 35.72.181.5
  port:
    dev: 8088
    prod: 8088
  pass_mixin: "0x00544"
pgsql:
  dev:  >-
    postgresql://postgres:emdb2scjdl@localhost:5432/emdb
  prod: >-
    postgresql://postgres:pwd@host:port/db_name?charset=utf8mb4
mongo:
  client:
    dev: "mongodb://admin:event_logs.likn.co@localhost:27017/admin"
    prod: "mongodb://admin:event_logs.likn.co@localhost:27017/admin"
  db:
    dev: "emdb"
    prod: "emdb"
swagger:
  path: '/path/to/swagger'
  ui_path: '/path/to/swagger-ui'
