project:
  name: emdb
log:
  path: "../../logs/"
  level: "Info"
debug:
  dev: true
  prod: false
server:
  domain:
    dev: 127.0.0.1
    prod: https://emdb.api.co
  host:
    dev: 127.0.0.1
    prod: 43.207.219.44
  port:
    dev: 8088
    prod: 8088
  pass_mixin: "0x00544"
pgsql:
  dev:  >-
    postgresql://postgres:emdb2scjdl@localhost:5432/emdb
  prod: >-
    postgresql://postgres:8BR53B9ErGweQH@43.207.219.44:5432/emdb
swagger:
  path: '/path/to/swagger'
  ui_path: '/path/to/swagger-ui'
