- code: 0
  msg: Success!
- code: 1
  msg: Fail!
- code: 400
  msg: Parameters Error!
- code: 401
  msg: Auth Error!
- code: 402
  msg: Bad Requests!
- code: 403
  msg: Unsupport Network!
- code: 404
  msg: Not Found!
- code: 405
  msg: Add Movie Fail!
- code: 407
  msg: Movie Already Exists!



